server:
  port: 8082
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # ?gateway????nacos?????
      routes: # ????[?? ???????????????????????]
        - id: product_route # ????????????
          uri: http://192.168.2.101:8081 # ?????????
          order: 1 # ???????????????
          predicates: # ??(????????????)
            - Path=/product-serv/**
          filters: # ????????????????????????????
            - StripPrefix=1 # ??????1???
#            - SetStatus=2000 # ?????????????????
            - Time=true
        - id: order_route
          uri: http://192.168.2.101:8081
          predicates:
            - Path=/order-serv/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: 192.168.2.101:8848